use Ejemplo;
----Creando la tabla persona------
CREATE TABLE TB_PERSONA(
	ID_PERSONA INT IDENTITY(1,1) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO_PATERNO VARCHAR(100) NOT NULL,
	APELLIDO_MATERNO VARCHAR(100),
	COD_DOI NUMERIC(8) NOT NULL,
	DIRECCION VARCHAR(255) NOT NULL,
	FEC_NACIMIENTO DATE,
	FEC_CREACION DATETIME NOT NULL,
	FEC_MODIFICACION DATETIME,
	CONSTRAINT PK_PERSONA PRIMARY KEY (ID_PERSONA),
	CONSTRAINT CK_PERSONA_FEC_MODIFICACION CHECK(FEC_MODIFICACION > FEC_CREACION),
)

-----------------------------------------------------------------------------

ALTER TABLE TB_PERSONA
	ADD SEXO CHAR(1) NOT NULL

ALTER TABLE TB_PERSONA
	ADD NUM_MOVIL NUMERIC(9) NOT NULL

ALTER TABLE TB_PERSONA
	ADD CONSTRAINT CK_PERSONA_SEXO CHECK (SEXO IN ('M','F'))

ALTER TABLE TB_PERSONA
	ADD CONSTRAINT CK_PERSONA_COD_DOI CHECK (LEN(COD_DOI) = 8)

ALTER TABLE TB_PERSONA
	ADD CONSTRAINT CK_PERSONA_NUM_MOVIL CHECK (LEN(NUM_MOVIL) = 9)

ALTER TABLE TB_PERSONA 
	ADD CONSTRAINT UI_PERSONA_COD_DOI UNIQUE (COD_DOI)

SELECT * FROM TB_PERSONA


-- Creando la tabla TB_TIPO_DOC_IDENTIDAD ----------
CREATE TABLE TB_TIPO_DOC_IDENTIDAD (
    ID_TIPO_DOC INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    CONSTRAINT PK_TIPO_DOC_IDENTIDAD PRIMARY KEY (ID_TIPO_DOC)
);

-- Insertar los registros DNI, CE, PAS
INSERT INTO TB_TIPO_DOC_IDENTIDAD (DESCRIPCION) VALUES ('DNI'), ('CE'), ('PAS');

-- Modificar la tabla TB_PERSONA:
-- Modificar la columna COD_DOI, pero antes eliminar las restricciones que usan este dato.
ALTER TABLE TB_PERSONA DROP CONSTRAINT CK_PERSONA_COD_DOI;
ALTER TABLE TB_PERSONA DROP CONSTRAINT UI_PERSONA_COD_DOI;

ALTER TABLE TB_PERSONA
    ALTER COLUMN COD_DOI VARCHAR(12) NOT NULL;
-- Agregar la columna ID_TIPO_DOC_IDENTIDAD y relacionarla con la tabla TB_TIPO_DOC_IDENTIDAD:
ALTER TABLE TB_PERSONA
    ADD ID_TIPO_DOC_IDENTIDAD INT NOT NULL,
    CONSTRAINT FK_PERSONA_TIPO_DOC_IDENTIDAD FOREIGN KEY (ID_TIPO_DOC_IDENTIDAD) REFERENCES TB_TIPO_DOC_IDENTIDAD(ID_TIPO_DOC);

-- Modificar la restricción de verificación CK_PERSONA_COD_DOI
-- para asegurarnme de que cada registro de persona tenga un tipo de documento de identidad válido.
-- Si el valor de COD_DOI no es válido para el tipo de documento seleccionado, se producirá un error de restricción CHECK
ALTER TABLE TB_PERSONA
    DROP CONSTRAINT CK_PERSONA_COD_DOI;

ALTER TABLE TB_PERSONA
	ADD CONSTRAINT CK_PERSONA_COD_DOI 
	CHECK (
		(ID_TIPO_DOC_IDENTIDAD = 1 AND LEN(COD_DOI) = 8) OR
		(ID_TIPO_DOC_IDENTIDAD IN (2, 3) AND LEN(COD_DOI) = 12)
	)

------ VISTA PERSONA --------
DROP VIEW VW_PERSONA;

CREATE VIEW VW_PERSONA AS
SELECT 
    ID_PERSONA,
    NOMBRE,
    APELLIDO_PATERNO,
    APELLIDO_MATERNO,
    COD_DOI,
    DIRECCION,
    FEC_NACIMIENTO,
    FEC_CREACION,
    FEC_MODIFICACION,
    SEXO,
    NUM_MOVIL,
    DESCRIPCION
FROM TB_PERSONA
INNER JOIN TB_TIPO_DOC_IDENTIDAD
ON ID_TIPO_DOC_IDENTIDAD = ID_TIPO_DOC;
--Mostrando vista----
SELECT * FROM VW_PERSONA;
---------------------------------------------------------------------------
-- DNI:
INSERT INTO TB_PERSONA (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, COD_DOI, DIRECCION, FEC_NACIMIENTO, FEC_CREACION, FEC_MODIFICACION, SEXO, NUM_MOVIL, ID_TIPO_DOC_IDENTIDAD)
VALUES ('Juan', 'Pérez', 'Gómez', '12345678', 'Av. Los Álamos 123', '1990-01-01', GETDATE(), '2023-07-01','M', 987654321, 1);
-- CE:
INSERT INTO TB_PERSONA (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, COD_DOI, DIRECCION, FEC_NACIMIENTO, FEC_CREACION, FEC_MODIFICACION, SEXO, NUM_MOVIL, ID_TIPO_DOC_IDENTIDAD)
VALUES ('Juanita', 'Pérez', 'Gómez', '123456789012', 'Av. Los Álamos 123', '1952-01-01', GETDATE(), '2025-07-01','M', 123456789, 2);
-- PAS:
INSERT INTO TB_PERSONA (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, COD_DOI, DIRECCION, FEC_NACIMIENTO, FEC_CREACION, FEC_MODIFICACION, SEXO, NUM_MOVIL, ID_TIPO_DOC_IDENTIDAD)
VALUES ('JuanSE', 'Javier', 'Gómez', '75391LK6805A', 'Av. Pacasmayo 1', '2000-01-01', GETDATE(), '2025-07-01','M', 939231736, 3);
---------------------------------------------------------------------------
--delete from tb_persona where nombre='Juan';
---------------------------------------------------------------------------
----Mostrando TB_TIPO_DOC_IDENTIDAD----
SELECT * FROM TB_TIPO_DOC_IDENTIDAD

----- Ejemplo del indice con 1M de registros..
CREATE TABLE CLIENTE(
	ID_CLIENTE INT PRIMARY KEY,
	NOMBRE VARCHAR(255)
)

SET NOCOUNT ON

DECLARE @contador INT  = 1

WHILE (@contador <= 1000000)
BEGIN
	DECLARE @ID_CLIENTE INT = @contador
	DECLARE @nombre VARCHAR(255) = 'Nombre ' + RTRIM(@contador)

	INSERT INTO CLIENTE (ID_CLIENTE,NOMBRE)
	VALUES (@ID_CLIENTE, @nombre)

	SET @contador = @contador + 1

	IF (@contador%100000 = 0)
		PRINT RTRIM(@contador) + ' filas insertadas.'
END

CREATE INDEX IX_CLIENTE_NOMBRE ON CLIENTE(NOMBRE)
CREATE INDEX NONCLUSTERED 



